### ISSUE TITLE
Provide an option to ignore `VersionNotFoundError`

### ISSUE THREAD

**Issue by coordt** [callowayproject/bump-my-version#10]
### Description

Based on [this issue](https://github.com/c4urself/bump2version/issues/267)

Add an `--ignore-missing` CLI option to silence these errors.

**Comment by kdeldycke** [comment]
I can confirm this issue.

Given this minimal project (which extends the one in #34):
```shell-session
$ ls
docs.yaml  empty.yaml  pyproject.toml
```

- `./docs.yaml` file contains:
  ```yaml 
  url: https://github.com/kdeldycke/workflows/main/.github/update_mailmap.py
  ```

- `./empty.yaml` is completely empty.

- `./pyproject.toml` contains:
  ```toml
  [tool.bumpversion]
  current_version = "2.17.7"
  allow_dirty = true
  ```

The following command fails:
```shell-session
$ bump-my-version replace --dry-run --search "/workflows/main/" --replace "/workflows/v{current_version}/" ./*.yaml

 Usage: bump-my-version replace [OPTIONS] [FILES]...

 Try 'bump-my-version replace --help' for help. 
╭─ Error ─────────────────────────────────────────────────╮
│ Did not find '/workflows/main/' in file: './empty.yaml' │
╰─────────────────────────────────────────────────────────╯
```

**Comment by kdeldycke** [comment]
Thanks @coordt for the new `--ignore-missing-version`!

I tried again the same example above with the new bump-my-version `0.8.0`, but adding `--ignore-missing-version` to my example above still produce the same error message:
```shell-session
$ bump-my-version replace --dry-run --no-configured-files --ignore-missing-version --search "/workflows/main/" --replace "/workflows/v{current_version}/" ./*.yaml

 Usage: bump-my-version replace [OPTIONS] [FILES]...

 Try 'bump-my-version replace --help' for help. 
╭─ Error ─────────────────────────────────────────────────╮
│ Did not find '/workflows/main/' in file: './empty.yaml' │
╰─────────────────────────────────────────────────────────╯
```

So I wonder, is `--ignore-missing-version` suppose to ignore the missing match of the constant string provided by `--search`? Or what I'm trying to do with `--ignore-missing-version` is another use-case entirely?
