### ISSUE TITLE
Conda package is not being kept up-to-date

### ISSUE THREAD

**Issue by Zeitsperre** [callowayproject/bump-my-version#129]
* bump-my-version version: 0.12.0
* Python version: Python3.11 (Conda)
* Operating System: Fedora

### Description

The Anaconda (conda-forge) packages for `bump-my-version` don't appear to have been updated since v0.12.0. These releases should follow at around the same frequency as releases of `bump-my-verison` on PyPI.

If you would like help maintaining the `conda` packages, please let me know.

### What I Did

```
$ conda install bump-my-version
```

### Additional Information

See: https://github.com/conda-forge/bump-my-version-feedstock/pulls

**Comment by coordt** [comment]
Got this fixed.
