### ISSUE TITLE
docs: monospaced section not parsed correctly

### ISSUE THREAD

**Issue by irons** [callowayproject/bump-my-version#175]
### Description

At https://callowayproject.github.io/bump-my-version/#visualize-the-pre_n-versioning-path, the depiction of `show-bump` output is parsed like a run-on sentence. The corresponding section at https://github.com/callowayproject/bump-my-version?tab=readme-ov-file#visualize-the-pre_n-versioning-path is OK. 

The difference might be due to a leading space before the closing triple backticks at [README.md:214](https://github.com/callowayproject/bump-my-version/blob/master/README.md?plain=1#L214). I tried to test that in a fork but ran out of time before I figured out how to get GitHub Pages to publish anything.

**Comment by coordt** [comment]
Thank you fr the feedback! It is rare to get any feedback on documentation. I appreciate it and will get it fixed today.
