### ISSUE TITLE
Zero-padded version parts are not working

### ISSUE THREAD

**Issue by coordt** [callowayproject/bump-my-version#179]
It seems that this fix was removed with some refactoring happened in #112. Tried with version 0.20.1 and the following config parameters:
```
current_version = "5.06.0"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor:02}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
```
Increasing minor would result in version 5.70.0 which is obviously wrong. Any chances we get this functionality back? Or is there any other possibility to have fixed length version numbers?

_Originally posted by @reindlt in https://github.com/callowayproject/bump-my-version/issues/26#issuecomment-2071756686_

**Comment by reindlt** [comment]
Thanks @coordt for opening the issue.

I guess it's related to the same problem as mentioned in https://github.com/callowayproject/bump-my-version/pull/26#issue-1772530821 that the version parts are handled as strings. A possible solution has been described here https://github.com/c4urself/bump2version/pull/141#issue-615092830. Does this sound reasonable?

**Comment by coordt** [comment]
It looks reasonable. I'll look at it today.
