### ISSUE TITLE
Feature Request: Provide option to perform tag prior to bumping the version and commit.

### ISSUE THREAD

**Issue by dawgware** [callowayproject/bump-my-version#200]
* bump-my-version version: 0.23.0
* Python version: All
* Operating System: All

### Description

We utilize Release Branching for our development lifecycle and we tag releases and patches from these branches. A release tag is generated off the current version in the branch, so the initial release tag would be x.y.1  and subsequent patches are x.y.2-n.

The problem I'm having with bump-my-version is that the version is bumped to **new_version** before performing the tag which makes the tag-name and app version incorrect in our workflow. What we need is the tag to be performed using **current_version** so the tag-name and the version in the app files would be consistent with our release stategy.
Most of our apps are maven projects and utilize _**maven release:prepare release:perform**_ which tags release first then updates the version for next iteration. I'm trying to replicate this process for our python apps.

I've reviewed the documentation and tested the application but I do not see a way to force the tag before bumping the version.

An option like `--tag-first` or `--tag-before-bump` would create the tag with the current_version, then bump the version and commit the new_version updates.

### What I Did
The workaround I've been using is to tag the release via git cli then bump the version and commit changes with bump-my-version.
This works but is cumbersome and would prefer the convenience of bump-my-version to handle both tagging and versioning.
```
    git tag -a ${_tag} -m "prepare release ${_tag}"
    git push origin tag ${_tag}
    bump-my-version bump patch --no-tag --config-file .bumpversion.toml 
    git push origin ${BRANCHTORELEASE}
```

**Comment by coordt** [comment]
@dawgware, could you possibly give me more information on the Release Branching process? I looked for information about how Maven does things and tried to find a good answer about the process. Any links to how the workflow works would be appreciated so I can get more context about this issue.

**Comment by coordt** [comment]
@dawgware I'm going to be releasing a new version that provides hooks for scripts to run during the process here: #228 

Feel free to look at it and let me know if you have any advice.

**Comment by coordt** [comment]
Version 0.26.0 should have what you need.
