### ISSUE TITLE
Issue with commiting with `pre-commit` enabled in the workspace

### ISSUE THREAD

**Issue by lnxpy** [callowayproject/bump-my-version#217]
* bump-my-version version: 0.21.1
* Python version: 3.12.3
* Operating System: MacOS

### Description

When I have `pre-commit` enabled, if my cache is empty, `pre-commit` clones the hooks and tries to use them for the rest of committing moments. Since `bump-my-version` uses the classic `git commit` command, it will trigger `pre-commit`. That's why if I'm not connected to the internet or don't have access to those pre-commit hooks repositories, bumping my version would stop in the committing stage. Then, I have to commit them on my own. Ultimately, do `git tag` because `git tag` happens after `git commit`.

This is what it raises after a few minutes:
```
Failed to run ['git', 'commit', '-F', '/var/folders/w8/1ylgn1zn1ks8qrqyt1w32gjc0000gn/T/tmpex2iowly']: return code 1,     │
│ output: b''
```

### Worth noting
Adding the `--no-verify` option when committing, won't trigger the `pre-commit` hooks.

```
git commit -m "..." --no-verify
```

**Comment by coordt** [comment]
You can add the `--no-verify` [argument to the configuration](https://callowayproject.github.io/bump-my-version/reference/configuration/#commit_args)

**Comment by lnxpy** [comment]
Nice! @coordt
