### ISSUE TITLE
Feature Request: bump-my-version show-bump --type <major/minor/patch> [VERSION]

### ISSUE THREAD

**Issue by hongjiaherng** [callowayproject/bump-my-version#231]
* bump-my-version version:
* Python version:
* Operating System:

### Description

None

### What I Did

Here's the current CLI options for `show-bump` in `bump-my-version`.
```
 Usage: bump-my-version show-bump [OPTIONS] [VERSION]

 Show the possible versions resulting from the bump subcommand.

╭─ Options ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ --config-file      FILE           Config file to read most of the variables from.                                                      │
│ --ascii                           Use ASCII characters only.                                                                           │
│ --verbose      -v  INTEGER RANGE  Print verbose logging to stderr. Can specify several times for more verbosity.                       │
│ --help         -h                 Show this message and exit.                                                                          │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

Is it possible to add a new option for specifying the exact bump type? For example:

```
bump-my-version show-bump --type patch v1.0.0 # it should gives v1.0.1 to stdout
```

It would be helpful for using it in CI as I don't want to have a actual file like `__init__.py` to track the version (no new commit in main branch after bumping version is created/needed). 

So the following is what I hope to achieve:
```
python --version
python -m venv .venv && source .venv/bin/activate && pip install --upgrade pip --quiet
pip install -U bump-my-version --quiet

git config user.email "${CI_BOT_EMAIL}"
git config user.name "${CI_BOT_USERNAME}"

git remote set-url --push origin https://${CI_BOT_TOKEN_NAME}:${CI_BOT_ACCESS_TOKEN}@gitlab.example.com/${CI_PROJECT_PATH}.git
git push origin tag v$(bump-my-version show-bump --type ${RELEASE_TYPE})     // by default, bump-my-version already can read latest version from git tag
```

Or even better, allow `bump-my-version` to create new tag without writing to a file. Then this can be achieved:
```
python --version
python -m venv .venv && source .venv/bin/activate && pip install --upgrade pip --quiet
pip install -U bump-my-version --quiet

git config user.email "${CI_BOT_EMAIL}"
git config user.name "${CI_BOT_USERNAME}"

bump-my-version bump $RELEASE_TYPE    // this will create a new git tag without explicit write to any file
git remote set-url --push origin https://${CI_BOT_TOKEN_NAME}:${CI_BOT_ACCESS_TOKEN}@gitlab.example.com/${CI_PROJECT_PATH}.git
git push origin tag v$(bump-my-version show current_version)
```

**Comment by coordt** [comment]
Two things::

1. The current, most straightforward way to get the version of a potential bump as you want it is with the `show` command. `bump-my-version show --increment minor new_version`. The `show` command is a legacy command that displays configuration information and allows one to show specific keys.
2. Your question about this demonstrates the overlap of the two commands. I may not be able to get to this for a week or two.

**Comment by hongjiaherng** [comment]
Hey @coordt, appreciate the prompt reply!

I can achieve what I'm trying to do with the provided command. Would you deprecate the legacy command in a very near future? If this ever get deprecated, this is my current workaround:

```
bump-my-version show-bump --ascii | grep $RELEASE_TYPE | awk '{print $NF}'     # $RELEASE_TYPE is either 'major', 'minor', or 'patch'
```

For 2, I'm willing to contribute if you need another helping hand on this. Anyway, this is not a very rushed requirement on my project too.

**Comment by reneleonhardt** [comment]
@hongjiaherng FYI my PR last year provided that exact functionality (show the next number for specific type):
https://github.com/callowayproject/bump-my-version/pull/88

**Comment by hdhakernk** [comment]
Hi @coordt 

I and my team are struggling  this same issue mentioned in https://github.com/callowayproject/bump-my-version/pull/88#issuecomment-1817534528

This unique feature in not available in any of the other package on pypi.

Adding this feature will significantly improve our CI pipeline.

Request you to please consider this feature.

**Comment by coordt** [comment]
@hdhakernk The feature in #88 was about a Docker file. This is now a part of the repository, along with a GitHub action to provide automation.

To preview a new version, you can use the command `bump-my-version show --increment <type> new_version` to see it.

I'm not sure exactly what you are requesting. Can you provide a bit more clarification?

**Comment by hdhakernk** [comment]
@coordt 
i was interested in a CI command where i can provide **current version** along with required parameter.
in response I'm expecting new version

Syntax: `bump-my-version show --increment <type> new_version --current_version "x.x.x"`

eg 1:  `bump-my-version show --increment minor new_version --current_version 1.0.0`
output: 1.1.0

eg 2:  `bump-my-version show new_version --increment patch  --current_version 1.0.0`
output: 1.1.0

we can keep rest of all the config parameter in `.config.toml` as it is.
only current version can be overwrite by a new parameter.
it will reduce effort to update current version in  config file in order to get new

**Comment by coordt** [comment]
To summarize, would it work for you if I added a `--current_version` option to the `bump-my-version show` command?

That should be an easy addition.

**Comment by hdhakernk** [comment]
@coordt 

same i am expecting.

**Comment by coordt** [comment]
Version 0.29.0 should have that capability.
