### ISSUE TITLE
how about add a short one command？

### ISSUE THREAD

**Issue by Atticuszz** [callowayproject/bump-my-version#249]
hello 😄
use bpmv or bpv as bump-my-version？
it looks more clean in command line

**Comment by coordt** [comment]
I'm not going to lie; I really like the suggestion.

However, changing the command's name impacts backward compatibility, and installing two different commands that do the same thing is frowned upon.

I recommend creating an [alias](https://www.geeksforgeeks.org/alias-command-in-linux-with-examples/).

**Comment by Atticuszz** [comment]
good idea 😄
