### ISSUE TITLE
uv.lock project version is outdated

### ISSUE THREAD

**Issue by johnhenaot** [callowayproject/bump-my-version#262]
https://github.com/callowayproject/bump-my-version/blob/704cd1446fef273be7732c389ed0050df0b74d6f/uv.lock#L131

As you can see in this same project (bump-my-version), the uv.lock version for bump-my-version is using a past version. This is the issue I am having right now. 

I have tried adding this in the section [tool.bumpversion] in my project.toml file:

`pre_commit_hooks = ["uv sync", "git add uv.lock"]`

Right now, the uv is still in the past version and my version in the section [project] of my project.toml file is not being updated either. Here is my full configuration in the project.toml file:

```
[tool.bumpversion]
current_version = "0.1.1"
search = "{current_version}"
replace = "{new_version}"
allow_dirty = false
commit = true
message = "Bumpversion: {current_version} → {new_version}"
tag = true
tag_name = "v{new_version}"
pre_commit_hooks = ["uv sync", "git add uv.lock"]

[[bumpversion.files]]
name = "pyproject.toml"
search = "version = {current_version}"
replace = "version = {new_version}"
```

**Comment by coordt** [comment]
Thanks for catching this! I've updated the `uv.lock` file and added a pre-commit hook to bump-my-version's setup.

I need to see the verbose logs to give you more information about your issues. Please add `--vv` to your bump command and post the results here.

**Comment by johnhenaot** [comment]
Thanks! All good now, I just used your pre commit hook.
