### ISSUE TITLE
Build on conda-forge?

### ISSUE THREAD

**Issue by MattF-NSIDC** [callowayproject/bump-my-version#46]
Howdy! I was very excited to find this project exists and is continuing the development of bumpversion. Thank you!

I was hoping to find this package distributed through conda-forge, but it's not available there.

I'd be happy to get the process started if nobody else is already working on it. I maintain a couple feedstocks on my personal account (@mfisher87), but have never created a new one. Can't be that hard, right?

**Comment by coordt** [comment]
@MattF-NSIDC I'm not familiar with the process and would love the help.

I created a [PR](https://github.com/conda-forge/staged-recipes/pull/23693) that I _think_ will start the process.

**Comment by mfisher87** [comment]
I'll try and make some time tonight to test. If you want to grant me push access on your fork, I can help with shepherding it through the process too! I'd like to add myself to the maintainer list in your recipe :)

**Comment by mfisher87** [comment]
Nice work on the recipe!

**Comment by coordt** [comment]
@mfisher87 I've added you as a maintainer on the fork.

**Comment by coordt** [comment]
Feel free to add yourself as a maintainer on the recipe as well

**Comment by mfisher87** [comment]
Thanks, done!

**Comment by mfisher87** [comment]
Feedstock is live: https://github.com/conda-forge/bump-my-version-feedstock

**Comment by mfisher87** [comment]
And I just installed `bump-my-version` with `mamba`. Nice work!

I thought I would be able to close this issue because I was the reporter, but I can't. @coordt would you close please?
