### ISSUE TITLE
Documentation currently behind (v0.8.0)

### ISSUE THREAD

**Issue by MattF-NSIDC** [callowayproject/bump-my-version#47]
Docs are currently for v0.8.0, but the current release is v0.9.2: https://callowayproject.github.io/bump-my-version/#

I'm excited about the new regex feature for updating my project's `CITATION.cff` `released-date` field (thank you for this!), but the docs are currently not online. I've been able to move forward from reading the documentation and code source, however.

PS: The documentation in the repo for the regex search is great, thank you for including examples :)

**Comment by MattF-NSIDC** [comment]
If it would be valuable to you, I'd be happy to open a PR that sets up GitHub Actions to automatically deploy the docs when pushes/merges to the default branch occur.

**Comment by coordt** [comment]
Thanks for noticing. I added that automatic doc-building workflow. Thanks for offering, though. I appreciate it.
