### ISSUE TITLE
Invalid regex errors with `--no-regex` option

### ISSUE THREAD

**Issue by kdeldycke** [callowayproject/bump-my-version#60]
* bump-my-version version: 0.9.3
* Python version: 3.11.15
* Operating System: macOS

### Description

It looks like the constant strings I am providing to `bump-my-version` in a search and replace operations are interpreted as regular expressions, even if I explicitely pass the `--no-regex` option.

### What I Did

Let starts with a simple `changelog.md` file containing:

```md
# Changelog

## [0.0.1 (unreleased)](https://cool.url)

- Test unreleased package.
```

Now let's replace the `(unreleased)` part of the URL label with the current date:

```shell-session
$ bump-my-version replace --no-regex --no-configured-files --current-version "0.0.1" --search " (unreleased)](" --replace " ({now:%Y-%m-%d})](" ./changelog.md
Invalid regex 're.compile('\\ \\(unreleased\\)\\]\\(', re.MULTILINE|re.DOTALL)' for file ./changelog.md: missing ), unterminated subpattern at position 14.                                                         
Invalid regex 're.compile('\\ \\(unreleased\\)\\]\\(', re.MULTILINE|re.DOTALL)' for file ./changelog.md: missing ), unterminated subpattern at position 14.                                                         
```

The invokation seems to work, and `changelog.md` file is now:
```md
# Changelog

## [0.0.1 (2023-08-29)](https://cool.url)

- Test unreleased package.
```

But I did not expect to have the error messages regarding regex compilation error.

**Comment by coordt** [comment]
@kdeldycke Is this still an issue with the 0.10.0 release?

**Comment by kdeldycke** [comment]
Yes, I can confirm 0.10.0 fix this issue. Let's close this, and thanks for 0.10.0!
