### ISSUE TITLE
Only have bump-my-version script

### ISSUE THREAD

**Issue by mauvilsa** [callowayproject/bump-my-version#69]
Since `bump-my-version` in many cases can be used to replace the no-longer-maintained projects, people might want to install in the same environment both `bump-my-version` and `bumpversion`. Currently this is problematic because `bump-my-version` overwrites the `bumpversion` command. Also, since `bump-my-version` has deviated from the previous projects, making the CLI calls incompatible, then there is little point in replacing that command. If people need to change the command arguments, then at the same time they can change the command name.

I propose to remove:
https://github.com/callowayproject/bump-my-version/blob/46be61b320801133d180facfc4a8fb6edded1f3a/pyproject.toml#L44

**Comment by kdeldycke** [comment]
I'm for this. `bump-my-version` already deviates a lot from the legacy `bumpversion` and co. It is its own tool, we can start removing these artefacts of the past.

**Comment by olutra** [comment]
It should be possible to split the scripts beetween two packages: keep `bump-my-version` in this project and move `bumpversion` to a separate package.
Then `pip install bump-my-version` will only provide the `bump-my-version` script, and something like `pip install bump-my-version[bumpversion]` will provide both scripts.
