### ISSUE TITLE
Allow tag without new commit

### ISSUE THREAD

**Issue by tkoft** [callowayproject/bump-my-version#82]
* bump-my-version version: 0.11.0
* Python version: 3.10.10
* Operating System: macOS Ventura

### Description

Trying to use bump-my-version just to determine the current_version based on the last git tag, bump it, and create a new tag on the current HEAD.  Bump2version did this fine, but it seems like bump-my-version [explicitly disallows tagging if you're not also committing. 
](https://github.com/callowayproject/bump-my-version/blob/master/bumpversion/scm.py#L166)

Not sure what the motivation for this is, plenty of projects add tags after committing especially when versioning through CI/CD.

### What I Did

```
% bump-my-version bump patch --tag
* no output *
```

**Comment by coordt** [comment]
`bump-my-version`'s committing and tagging are more related to the fact it is also changing files, its own configuration being one. It is designed to tag the commit it creates, not a different commit.

Can you describe how your workflow works for tracking versions and where you see `bump-my-version`'s role?

**Comment by coordt** [comment]
Closing due to lack of understanding
