### ISSUE TITLE
Trying to modify several files resulted in no updated version string

### ISSUE THREAD

**Issue by jfmoulin** [callowayproject/bump-my-version#84]
* bump-my-version version: 0.11.0
* Python version: 3.10.12
* Operating System: Linux Mint 21.1

### Description
Trying to modify several files resulted in no updated version string
### What I Did
Using the following pyproj.toml and invoking bumpmyversion -v patch resulted in a correct git commit (8.0.1) but in  the files  (setup.py and ./mypackage/__init_.py)   the version string was not updated (still 8.0.0).
Earlier modifying only a single file (the local setup.py), things where updated properly
Do I miss something obvious in the syntax?
 
```
[build-system]
requires = ["setuptools>=67.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.bumpversion]
current_version = "8.0.0"
file = "setup.py ./mypackage/__init__.py"
commit = true
tag = true


```

**Comment by coordt** [comment]
I think you need to look at [your configuration](https://callowayproject.github.io/bump-my-version/reference/configuration.html#toml-configuration-files). It seems like you have misconfigured the files.

Also you can also run `bump-my-version -v -n patch` to make it do a dry run.
