### ISSUE TITLE
`0.12.0` wasn't tagged

### ISSUE THREAD

**Issue by kdeldycke** [callowayproject/bump-my-version#89]
* bump-my-version version: `0.12.0`

### Description

A minor issue: I just realized 0.12.0 has been release on PyPi. See: https://pypi.org/project/bump-my-version/0.12.0/

But its corresponding tag hasn't been created on this repository. Neither is the GitHub release.

### What I Did

The following URLs are 404:
* https://github.com/callowayproject/bump-my-version/tree/0.12.0
* https://github.com/callowayproject/bump-my-version/releases/tag/0.12.0

**Comment by coordt** [comment]
Fixed.
